application:
  port: 8000
  host: 127.0.0.1
database:
  host: 127.0.0.1
  port: 3306
  username: user
  password: pass
  database_name: newsletter
email:
  base_url: "https://api.postmarkapp.com"
  sender_email: user@example.com
