application:
  port: 8000
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: 127.0.0.1
  port: 3306
  username: user
  password: pass
  database_name: newsletter
email:
  base_url: "https://api.postmarkapp.com"
  sender_email: user@example.com
  authorization_token: "your token value here"
  timeout_milliseconds: 10000
